### ISSUE TITLE
Requested Windows Runtime type 'libVLCX.Instance' is not registered.

### ISSUE THREAD

**Issue by cbordeman** [kakone/VLC.MediaElement#35]
When loading my XAML, I get the error:

Requested Windows Runtime type 'libVLCX.Instance' is not registered.

What in the world does this mean?  I used the Nuget package VLC.MediaElement 0.9.15 and here's my xaml:

 <vlc:MediaElement x:Name="Player" AreTransportControlsEnabled="True" AutoPlay="True"/>

This happens during XAML parse/build before I set a Source.

**Comment by kakone** [comment]
Only at design time ? It works at runtime ?

**Comment by cbordeman** [comment]
Doesn't work at runtime.  I don't use the designer.

**Comment by cbordeman** [comment]
I opened the designer and it shows the following error.  My page only has the single vlc element on it so the vlc:MediaElement is the only thing on the page, has to be generating the error.  I don't use any design time data either.

ArgumentException: Value does not fall within the expected range.
Stack Trace:
at Windows.UI.Xaml.Hosting.XamlUIPresenter.SetSize(Int32 width, Int32 height)
   at Microsoft.VisualStudio.DesignTools.WindowsXamlDesigner.Views.WindowsUIXamlImageHost.RenderWorker()
   at Microsoft.VisualStudio.DesignTools.WindowsXamlDesigner.Views.WindowsUIXamlImageHost.RenderScheduler.OnRender(Object object)
   at Microsoft.VisualStudio.DesignTools.WindowsXamlDesigner.Views.WindowsUIXamlImageHost.RenderScheduler.<ScheduleRender>b__26_0(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by cbordeman** [comment]
If I take the AutoPlay="True" OFF then the designer works fine.  The runtime error still occurs, though.

**Comment by cbordeman** [comment]
I've read that when you add a nuget package the IDE adds a registration for the class to the .appxmanifest file.  However I don't see that in there.  And when I created my own component in C++ I never had to register it, I just used it as any other assembly (though mine wasn't a control, it was a simple class).

**Comment by cbordeman** [comment]
OK, must have been a compilation glitch or something because the error has blissfully disappeared.  Thanks.
