### ISSUE TITLE
Exception when running on Windows 10 Mobile (ARM)

### ISSUE THREAD

**Issue by TheOriginalAppStar** [kakone/VLC.MediaElement#4]
I get an exception, `Requested Windows Runtime type 'libVLCX.Instance' is not registered.`, when debugging on my Windows 10 Mobile (ARM) device from Visual Studio. The app deploys successfully, but the exception occurs as soon as the app loads.

Stack trace:
`   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at libVLCX.Instance..ctor(IList'1 argv, SwapChainPanel panel)
   at VLC.MediaElement.<Init>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VLC.MediaElement.<>c__DisplayClass88_0.<<OnApplyTemplate>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()`

Inner exception:
`Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))`

**Comment by kakone** [comment]
Yes, I need a new ARM build of libVLC for UWP to correct this.

**Comment by cansado2930** [comment]
Is there some progress about ARM?

**Comment by touseefbsb** [comment]
I also wanted to ask this, is there any progress? I mean when will this library be able to run on uwp mobile version? Thanks

**Comment by kakone** [comment]
I had a new build for ARM but it was too buggy. I prefer to not include it for now. The latest version of VLC for UWP (2.5.3) seems better, I will ask the ARM dlls.

**Comment by touseefbsb** [comment]
Yes please do ask fr them.and include them in this library. Thanks

**Comment by touseefbsb** [comment]
when will ARM build be included?

**Comment by cansado2930** [comment]
Are there any news with arm?

**Comment by touseefbsb** [comment]
a request to the admin that if there will be no arm package here then kindly close this issue so we can know otherwise kindly let us know about the progress. @kakone

**Comment by ZhaoYunxiong** [comment]
When will ARM dlls be included? I tried to look for it ,but I didn't find it in the nightly build of VLC.
The ARM build address provided by VLC-WinRt cannot be accessed

**Comment by cansado2930** [comment]
Yes, I searched it this summer and I had the same problem. If I search information about it and I found that @kakone requested 2 months ago the DLLs to other Developer but I haven't been able to find public DLLs . And I tried to compile it but I couldn't because there aren't enough information in order to compile and it launchs me a lot of errors :(

**Comment by kakone** [comment]
Yes, there are no nightly build for the ARM version. As indicated in the [README file](https://code.videolan.org/videolan/vlc-winrt/blob/master/README), some ARM builds were here : http://people.videolan.org/~hugo/ but it doesn't seem to work anymore. I'm asking to [Hugo](https://code.videolan.org/chouquette) or [Steve](https://code.videolan.org/robUx4) if they can do an ARM build for us (cf https://code.videolan.org/videolan/vlc-winrt/issues/207).

**Comment by kakone** [comment]
You can use the latest [libVLCX](https://www.nuget.org/packages/libVLCX) NuGet package, it should work on ARM.

**Comment by touseefbsb** [comment]
can you please update this repo with this latest package? Thanks

**Comment by kakone** [comment]
I don't understand, this repo is up to date. You just need to update the libVLCX dependency NuGet package.
